Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,12 +48,29 @@ jobs:
                   [[ -n "${GROUPID}" ]] || (echo "Could not determine Security Group ID" && exit 0);
                                                       
                   # Adding Rule SSH to Your Security Group
-                  echo Allowing CircleCI Build to access port 22 from IP $IP to the security group $GROUPID
+                  echo Allowing CircleCI_Build to access port 22 from IP $IP to the security group $GROUPID
                   aws ec2 authorize-security-group-ingress --group-id $GROUPID --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "'$LATEST_IP/32'", "Description": "'CircleCI_Build'"}]}]'                 
       - run:
           name: Move build artifacts to staging server
           command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r _site/* perfect-fit@prep.mapc.org:/var/www/perfect-fit
-      
+      - run:
+              name: AWS whitelist remove CircleCI IP
+              command: |
+
+                  # Get the public ip address
+                  LATEST_IP=$(wget -qO- http://checkip.amazonaws.com)
+                  IP=${IP-$LATEST_IP}
+                  [[ -n "$IP" ]] || (echo "Could not find your public IP" && exit 1);
+                  
+                  GROUPID=sg-e9bc309e
+                  [[ -n "$GROUPID" ]] || (echo "Could not determine Security Group ID" && exit 1);
+
+
+                  echo "Removing CircleCI_Build access from IP $IP to the security group $GROUPID"
+
+                  # Delete IP rules matching port
+                  aws ec2 revoke-security-group-ingress --group-id $GROUPID --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "'$LATEST_IP/32'", "Description": "'CircleCI_Build'"}]}]'
+              when: always
 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
